imageTag: "16.4"
postgresDatabase: fabric_ca

primary:
  persistence:
    storageClass: "fast-disks"
    size: 1Gi
  service:
    type: NodePort

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm: 
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app: postgresql
