image:
  tag: 2.1.0

# No ingress

persistence:
  acessMode: ReadWriteOnce
  Size: 1Gi
  storageClass: "fast-disk"

caName: ca

db:
  chart: ca-pg-postgresql

config:
  hlfToolsVersion: 2.1.0
  csr:
    names:
      c: IE
      st: Dublin
      l:
      o: "AID:Tech"
      ou: Blockchain
  affiliations:
    aidtech: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 95
        podAffinityTerm: 
          topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app: hlf-ca
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: release
                operator: In
                values:
                  - ca-pg
          topologyKey: "kubernetes.io/hostname"
