---
- name: Criar e montar imagem de disco
  hosts: all
  become: yes
  tasks:
    - name: Criar arquivo de imagem de 3GB
      command: dd if=/dev/zero of=/root/disk.img bs=1M count=3072
      args:
        creates: /root/disk.img

    - name: Verificar se a imagem já está formatada
      command: blkid /root/disk.img
      register: img_info
      failed_when: img_info.rc > 1
      changed_when: false
      ignore_errors: true

    - name: Formatar a imagem como ext4
      command: mkfs.ext4 /root/disk.img
      when: img_info.rc != 0

    - name: Criar diretório de montagem
      file:
        path: /mnt/disk-0
        state: directory

    - name: Associar imagem a um dispositivo de loop
      command: losetup --find --show /root/disk.img
      register: loop_device
      changed_when: false

    - name: Montar a imagem no diretório
      mount:
        path: /mnt/disk-0
        src: "{{ loop_device.stdout }}"
        fstype: ext4
        opts: loop
        state: mounted

    - name: Verificar espaço em disco
      command: df -h
      register: disk_usage

    - name: Exibir espaço em disco
      debug:
        msg: "{{ disk_usage.stdout_lines | select('search', '/mnt/disk-0') | list }}"
