apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fast-disks
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: fast-disks
  local:
    path: /mnt/disk-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-10-0-0-100
          - ip-10-0-0-101
          - ip-10-0-0-102
          - ip-10-0-0-103
          - ip-10-0-0-104

          