- name: Install workers
  hosts: workers
  become: yes
  tasks:

    - name: Add Kubernetes APT repository key
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes APT repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Prevent automatic updates for kubelet, kubeadm, and kubectl
      command: apt-mark hold kubelet kubeadm kubectl

- name: add node in cluster
  hosts: control_plane
  become: yes
  tasks:
    - name: generate token
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Save in file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /tmp/kubeadm_join.sh
        mode: '0644'

- name: Add new node in cluster
  hosts: workers
  become: yes
  tasks:
    - name: Get join command
      delegate_to: control_plane
      command: cat /tmp/kubeadm_join.sh
      register: join_command

    - name: join cluster
      command: "{{ join_command.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Get private IP of the node
      shell: hostname -I | awk '{print $1}'
      register: private_ip

    - name: Add worker label
      delegate_to: control_plane
      shell: KUBECONFIG=/etc/kubernetes/admin.conf kubectl label nodes ip-{{ private_ip.stdout | replace('.', '-') }} node-role.kubernetes.io/worker=
